In [1]:
import math
print("It's math! It has a type {}".format(type(math)))

It's math! It has a type <class 'module'>


In [2]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [3]:
print("pi with 4 digits, {:.4}".format(math.pi))

pi with 4 digits, 3.142


In [4]:
print(math.log(32,2))

5.0


In [5]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [6]:
import math as mt
print(mt.pi)

3.141592653589793


In [8]:
from math import *
print(pi,log(32,2))

3.141592653589793 5.0


In [9]:
from math import *
from numpy import *
print(pi,log(32,2))

TypeError: return arrays must be of ArrayType

In [10]:
#solution
from math import pi,log
from numpy import asarray
print(pi,log(32,2))

3.141592653589793 5.0


In [24]:
import numpy
print("numpy.random is a ",type(numpy.random))
print("it contains name such as ...",dir(numpy.random)[15])

numpy.random is a  <class 'module'>
it contains name such as ... binomial


In [25]:
rolls=numpy.random.randint(low=1,high=6,size=10)
rolls

array([2, 4, 3, 3, 1, 4, 5, 1, 1, 3])

In [26]:
type(rolls)

numpy.ndarray

In [27]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [28]:
rolls.mean()

2.7

In [29]:
rolls.tolist()

[2, 4, 3, 3, 1, 4, 5, 1, 1, 3]

In [31]:
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



In [32]:
rolls+10

array([12, 14, 13, 13, 11, 14, 15, 11, 11, 13])

In [39]:
xlist=[
    [1,2,3],
    [2,4,6],
]
x=numpy.asarray(xlist)
print("xlist={}\nx={}".format(xlist,x))

xlist=[[1, 2, 3], [2, 4, 6]]
x=[[1 2 3]
 [2 4 6]]


In [35]:
x[1,-1]

6

In [36]:
x[1,2]

6

In [40]:
xlist[1,-1]

TypeError: list indices must be integers or slices, not tuple